export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_SORT_REQUEST = 'PRODUCT_SORT_REQUEST';
export const PRODUCT_SORT_SUCCESS = 'PRODUCT_SORT_SUCCESS';
export const PRODUCT_SORT_FAIL = 'PRODUCT_SORT_FAIL';